spring:
  application:
    name: activity_manage
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdatabase?useUnicode=ture&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8081
logging:
  level:
    com.fhf.activity_manage.mapper.*: debug